// default-types.js — 11 vorinstallierte RPG Entity-Typ Schemas

export const DEFAULT_ENTITY_TYPES = [
  {
    id: 'charakter',
    name: 'Charakter',
    icon: '🧙',
    color: '#e94560',
    builtIn: true,
    fields: [
      { key: 'name', type: 'string', required: true, label: 'Name' },
      { key: 'geschlecht', type: 'enum', options: ['männlich', 'weiblich', 'futa'], label: 'Geschlecht' },
      { key: 'rasse', type: 'string', label: 'Rasse' },
      { key: 'klasse', type: 'string', label: 'Klasse' },
      { key: 'level', type: 'number', min: 1, max: 999, label: 'Level' },
      { key: 'hp', type: 'number', min: 0, max: 100, label: 'HP', display: 'bar' },
      { key: 'mana', type: 'number', min: 0, max: 100, label: 'Mana', display: 'bar' },
      { key: 'hunger', type: 'number', min: 0, max: 100, label: 'Hunger', display: 'bar' },
      { key: 'durst', type: 'number', min: 0, max: 100, label: 'Durst', display: 'bar' },
      { key: 'sauberkeit', type: 'number', min: 0, max: 100, label: 'Sauberkeit', display: 'bar' },
      { key: 'erregung', type: 'number', min: 0, max: 100, label: 'Erregung', display: 'bar' },
      { key: 'sperma_menge', type: 'number', min: 0, max: 100, label: 'Sperma-Menge', display: 'bar', condition: { field: 'geschlecht', in: ['männlich', 'futa'] } },
      { key: 'persoenlichkeit', type: 'text', label: 'Persönlichkeit' },
      { key: 'aussehen', type: 'text', label: 'Aussehen' },
      { key: 'wichtig', type: 'text', label: 'Wichtige Info' },
      { key: 'inventar', type: 'text', label: 'Inventar' },
      { key: 'tags', type: 'string', label: 'Tags (kommagetrennt)' },
      { key: 'portrait', type: 'image', label: 'Portrait' },
    ],
  },
  {
    id: 'beziehung',
    name: 'Beziehung',
    icon: '🕸️',
    color: '#c77dff',
    builtIn: true,
    fields: [
      { key: 'von', type: 'relation', relationType: 'charakter', required: true, label: 'Von (Charakter)' },
      { key: 'zu', type: 'relation', relationType: 'charakter', required: true, label: 'Zu (Charakter)' },
      { key: 'art', type: 'enum', options: ['Freund', 'Feind', 'Romanze', 'Familie', 'Mentor', 'Rivale', 'Sklave', 'Herr', 'Verbündeter', 'Geschäftspartner', 'Unbekannt'], label: 'Art' },
      { key: 'intensitaet', type: 'number', min: 0, max: 100, label: 'Intensität', display: 'bar' },
      { key: 'beschreibung', type: 'text', label: 'Beschreibung' },
      { key: 'geschichte', type: 'text', label: 'Gemeinsame Geschichte' },
    ],
  },
  {
    id: 'ort',
    name: 'Ort',
    icon: '📍',
    color: '#00d2ff',
    builtIn: true,
    fields: [
      { key: 'name', type: 'string', required: true, label: 'Name' },
      { key: 'typ', type: 'enum', options: ['Stadt', 'Dorf', 'Dungeon', 'Wildnis', 'Gebäude', 'Raum', 'Region', 'Kontinent'], label: 'Typ' },
      { key: 'beschreibung', type: 'text', label: 'Beschreibung' },
      { key: 'events', type: 'text', label: 'Was hier geschah' },
      { key: 'npcs', type: 'text', label: 'Bekannte NPCs hier' },
      { key: 'bild', type: 'image', label: 'Bild' },
    ],
  },
  {
    id: 'quest',
    name: 'Quest',
    icon: '📜',
    color: '#f0a500',
    builtIn: true,
    fields: [
      { key: 'name', type: 'string', required: true, label: 'Name' },
      { key: 'ziel', type: 'text', label: 'Ziel' },
      { key: 'status', type: 'enum', options: ['aktiv', 'abgeschlossen', 'fehlgeschlagen'], label: 'Status' },
      { key: 'naechstes_ziel', type: 'text', label: 'Nächstes Ziel' },
      { key: 'beteiligte', type: 'text', label: 'Beteiligte Charaktere' },
      { key: 'belohnung', type: 'text', label: 'Belohnung' },
      { key: 'notizen', type: 'text', label: 'Notizen' },
    ],
  },
  {
    id: 'item',
    name: 'Item',
    icon: '🎒',
    color: '#6bcb77',
    builtIn: true,
    fields: [
      { key: 'name', type: 'string', required: true, label: 'Name' },
      { key: 'typ', type: 'enum', options: ['Waffe', 'Rüstung', 'Trank', 'Nahrung', 'Schlüssel', 'Werkzeug', 'Magisch', 'Material', 'Schatz', 'Sonstiges'], label: 'Typ' },
      { key: 'besitzer', type: 'relation', relationType: 'charakter', label: 'Besitzer' },
      { key: 'beschreibung', type: 'text', label: 'Beschreibung' },
      { key: 'eigenschaften', type: 'text', label: 'Eigenschaften / Stats' },
      { key: 'wert', type: 'number', min: 0, label: 'Wert (Gold)' },
      { key: 'bild', type: 'image', label: 'Bild' },
    ],
  },
  {
    id: 'event',
    name: 'Event',
    icon: '📖',
    color: '#ff6b6b',
    builtIn: true,
    fields: [
      { key: 'name', type: 'string', required: true, label: 'Name / Titel' },
      { key: 'beschreibung', type: 'text', label: 'Was ist passiert?' },
      { key: 'kategorie', type: 'enum', options: ['Kampf', 'Entdeckung', 'Plot-Twist', 'Dialog', 'Handel', 'Tod', 'Reise', 'Begegnung', 'Sonstiges'], label: 'Kategorie' },
      { key: 'beteiligte', type: 'text', label: 'Beteiligte' },
      { key: 'ort', type: 'relation', relationType: 'ort', label: 'Ort' },
      { key: 'nachricht_nr', type: 'number', label: 'Nachricht #' },
      { key: 'zeitpunkt', type: 'string', label: 'In-Game Zeitpunkt' },
    ],
  },
  {
    id: 'fraktion',
    name: 'Fraktion',
    icon: '⚔️',
    color: '#ffd93d',
    builtIn: true,
    fields: [
      { key: 'name', type: 'string', required: true, label: 'Name' },
      { key: 'typ', type: 'enum', options: ['Gilde', 'Königreich', 'Orden', 'Bande', 'Religion', 'Handelshaus', 'Sonstiges'], label: 'Typ' },
      { key: 'beschreibung', type: 'text', label: 'Beschreibung' },
      { key: 'mitglieder', type: 'text', label: 'Bekannte Mitglieder' },
      { key: 'beziehungen', type: 'text', label: 'Beziehungen zu anderen Fraktionen' },
      { key: 'hauptsitz', type: 'relation', relationType: 'ort', label: 'Hauptsitz' },
    ],
  },
  {
    id: 'geschaeft',
    name: 'Geschäft',
    icon: '🏪',
    color: '#ff9a3c',
    builtIn: true,
    fields: [
      { key: 'name', type: 'string', required: true, label: 'Name' },
      { key: 'ort', type: 'relation', relationType: 'ort', label: 'Ort' },
      { key: 'haendler', type: 'relation', relationType: 'charakter', label: 'Händler' },
      { key: 'waren', type: 'text', label: 'Waren / Angebot' },
      { key: 'preise', type: 'text', label: 'Preise / Besonderheiten' },
      { key: 'transaktionen', type: 'text', label: 'Bisherige Transaktionen' },
    ],
  },
  {
    id: 'dungeon',
    name: 'Dungeon',
    icon: '🏰',
    color: '#8b5cf6',
    builtIn: true,
    fields: [
      { key: 'name', type: 'string', required: true, label: 'Name' },
      { key: 'beschreibung', type: 'text', label: 'Beschreibung' },
      { key: 'raeume', type: 'text', label: 'Bekannte Räume' },
      { key: 'monster', type: 'text', label: 'Monster / Gegner' },
      { key: 'fallen', type: 'text', label: 'Fallen' },
      { key: 'loot', type: 'text', label: 'Gefundener Loot' },
      { key: 'fortschritt', type: 'enum', options: ['Unentdeckt', 'Teilweise erkundet', 'Abgeschlossen', 'Boss besiegt'], label: 'Fortschritt' },
      { key: 'ort', type: 'relation', relationType: 'ort', label: 'Ort / Region' },
      { key: 'bild', type: 'image', label: 'Karte / Bild' },
    ],
  },
  {
    id: 'intimitaet',
    name: 'Intimität',
    icon: '💜',
    color: '#ff69b4',
    builtIn: true,
    fields: [
      { key: 'name', type: 'string', required: true, label: 'Titel / Beschreibung' },
      { key: 'person_a', type: 'relation', relationType: 'charakter', required: true, label: 'Person A' },
      { key: 'person_b', type: 'relation', relationType: 'charakter', required: true, label: 'Person B' },
      { key: 'ort', type: 'relation', relationType: 'ort', label: 'Ort' },
      { key: 'kontext', type: 'text', label: 'Kontext / Situation' },
      { key: 'details', type: 'text', label: 'Details' },
      { key: 'nachricht_nr', type: 'number', label: 'Nachricht #' },
      { key: 'zeitpunkt', type: 'string', label: 'In-Game Zeitpunkt' },
    ],
  },
  {
    id: 'rueckblick',
    name: 'Rückblick',
    icon: '📖',
    color: '#4ecca3',
    builtIn: true,
    fields: [
      { key: 'name', type: 'string', required: true, label: 'Session / Titel' },
      { key: 'zusammenfassung', type: 'text', required: true, label: 'Zusammenfassung' },
      { key: 'wichtige_events', type: 'text', label: 'Wichtige Ereignisse' },
      { key: 'beteiligte', type: 'text', label: 'Beteiligte Charaktere' },
      { key: 'von_nachricht', type: 'number', label: 'Von Nachricht #' },
      { key: 'bis_nachricht', type: 'number', label: 'Bis Nachricht #' },
    ],
  },
];
